### ISSUE TITLE
450万円程度で税金計算時にエラーになる問題を修正

### ISSUE THREAD

**Issue by sakamomo554101** [sakamomo554101/real_estate_investment_simulator#11]
# エラー内容

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 562, in _run_script
    exec(code, module.__dict__)
  File "/workspace/src/dashboard.py", line 50, in <module>
    dashboard()
  File "/workspace/src/dashboard.py", line 30, in dashboard
    dfs = executor.execute()
  File "/workspace/src/executor.py", line 30, in execute
    df = tc.calculate()
  File "/workspace/src/calculator.py", line 399, in calculate
    df = income_df.apply(calc_tax, axis=1)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/frame.py", line 9558, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/usr/local/lib/python3.10/site-packages/pandas/core/apply.py", line 741, in apply
    return self.apply_standard()
  File "/usr/local/lib/python3.10/site-packages/pandas/core/apply.py", line 868, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/usr/local/lib/python3.10/site-packages/pandas/core/apply.py", line 884, in apply_series_generator
    results[i] = self.f(v)
  File "/workspace/src/calculator.py", line 392, in calc_tax
    out_s["所得税"] = calc_income_tax(taxable_income=out_s["課税所得"])
  File "/workspace/src/util.py", line 44, in calc_income_tax
    raise ValueError(f"{taxable_income} is invalid value!")
```

**Comment by sakamomo554101** [comment]
あ、これ、給与が0円の際に問題になってるんだな。
んー、とりあえず課税所得がマイナスの場合に0円にするようにするかなぁ。

**Comment by sakamomo554101** [comment]
#12 で対応
